spring:
  application:
    name: Config-default
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true      #this is also bydefault true
    service-url:
      defaultZone: http://localhost:8761/eureka
